version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

node_docker_image: &node_docker_image
  docker:
    - image: cimg/node:12.16

commands:
  install_aws_cli:
    description: Configure aws cli to deploy resources
    steps:
      - run:
          name: install aws cli
          command: pip install awscli
  
  destroy-serverless-deployment:
    description: Destroy back-end cloudformation stacks given a workflow ID.    
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
              aws s3 rm "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
              aws cloudformation delete-stack --stack-name udapeople-frontend-stack-${CIRCLE_WORKFLOW_ID:0:7}
              aws cloudformation delete-stack --stack-name udapeople-backend-stack-${CIRCLE_WORKFLOW_ID:0:7}

jobs:
  build-backend:
    <<: *node_docker_image
    steps:
      - checkout
      - restore_cache:
          key: backend-build-{{ checksum "./backend/package.json" }}
      - run:
          name: Build back-end
          command: |
            cd ./backend && npm install
      - save_cache:
          paths: 
            - ./node_modules
          key: backend-build-{{ checksum "./backend/package.json" }}

  build-frontend:
    <<: *node_docker_image
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./client/package.json" }}
      - run:
          name: Build front-end
          command: |
            cd ./client && npm install
      - save_cache:
          paths: 
            - ./node_modules
          key: frontend-build-{{ checksum "./client/package.json" }}

workflows:
  deployment-workflow:
    jobs:
      - build-backend:
          filters:
            branches:
              only: [main, dev]
      - build-client:
          filters:
            branches:
              only: [main, dev]

