version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
  aws-cli: circleci/aws-cli@3.1

node_docker_image: &node_docker_image
  docker:
    - image: cimg/node:12.16
      user: root

commands:
  install_aws_cli:
    description: Configure aws cli to deploy resources
    steps:
      - run:
          name: install aws cli
          command: pip install awscli
  
  destroy-serverless-deployment:
    description: Destroy back-end cloudformation stacks given a workflow ID.    
    steps:
      - run:
          name: Destroy environments
          when: on_fail
          command: |
              aws s3 rm "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
              aws cloudformation delete-stack --stack-name udapeople-frontend-stack-${CIRCLE_WORKFLOW_ID:0:7}
              aws cloudformation delete-stack --stack-name udapeople-backend-stack-${CIRCLE_WORKFLOW_ID:0:7}

jobs:
  build-backend:
    <<: *node_docker_image
    steps:
      - checkout
      - restore_cache:
          key: backend-build-{{ checksum "./backend/package.json" }}
      - run:
          name: Build back-end
          command: |
            cd ./backend && npm install
      - save_cache:
          paths: 
            - ./node_modules
          key: backend-build-{{ checksum "./backend/package.json" }}

  build-client:
    <<: *node_docker_image
    steps:
      - checkout
      - restore_cache:
          key: frontend-build-{{ checksum "./client/package.json" }}
      - run:
          name: Build front-end
          command: |
            cd ./client && npm install
      - save_cache:
          paths: 
            - ./node_modules
          key: frontend-build-{{ checksum "./client/package.json" }}
  
  deploy-serverless-backend:
    <<: *node_docker_image
    steps:
      - checkout
      - restore_cache:
          key: backend-build-{{ checksum "./backend/package.json" }}
      - run:
          name: Install serverless
          command: npm install -g serverless@2.21.1      
      - run:
          name: Update env vars in serverless.yml
          command: |
            cd ./backend &&\
            cat serverless_temp.yml |\
            sed "s|ENV_NAME|${ENV}|\
            g;s|AWS_REGION|${AWS_REGION}|g" > serverless.yml &&\
            cat serverless.yml
      - run:
          name: Install serverless plugins
          command: |
            cd ./backend &&\
            npm install serverless-webpack &&\
            npm install serverless-aws-documentation &&\
            npm install serverless-iam-roles-per-function &&\
            npm install serverless-plugin-tracing &&\
            npm install serverless-reqvalidator-plugin
      - run: 
          name: Configure serverless 
          command: |
            cd ./backend &&\
            sls config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_KEY_VALUE}
      - run:
          name: Deploy backend
          command: cd ./backend && serverless deploy --aws-region ${AWS_REGION}
      


workflows:
  deployment-workflow:
    jobs:
      - build-backend:
          filters:
            branches:
              only: [main, dev]
      - build-client:
          filters:
            branches:
              only: [main, dev]
      - deploy-serverless-backend:
          requires: [build-backend]

