apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-app
  name: client-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
  selector:
    app: client-app
  sessionAffinity: None
  type: LoadBalancer